import { ResumeContent } from '../../src/app/core/models/resume.model';

/**
 * Rich sample content used by CLI scripts (previews, thumbnails, contact
 * sheets). Covers every optional section so generated visuals exercise the
 * full renderer.
 */
export const sampleContent: ResumeContent = {
  contacts: {
    fullName: 'Jane Doe',
    title: 'Senior Software Engineer',
    email: 'jane@example.com',
    phone: '+1 555 0100',
    location: 'Seattle, WA',
    linkedinUrl: 'https://linkedin.com/in/janedoe',
    githubUrl: 'https://github.com/janedoe',
    portfolioUrl: '',
  },
  summary:
    'Results-driven Senior Software Engineer with 8+ years of experience building scalable web applications. Proven track record of delivering high-quality software solutions in fast-paced environments. Skilled in full-stack development, cloud architecture, and cross-functional team leadership.',
  skills: [
    'Angular',
    'TypeScript',
    'Node.js',
    'Python',
    'AWS',
    'React',
    'PostgreSQL',
    'Docker',
    'Kubernetes',
  ],
  experiences: [
    {
      id: 'e-1',
      company: 'Acme Corp',
      role: 'Senior Software Engineer',
      location: 'Seattle, WA',
      startDate: '2021-01',
      endDate: '',
      current: true,
      bullets: [
        'Led architecture for customer portal serving 500k+ monthly active users.',
        'Mentored a team of 5 engineers, improving team velocity by 30%.',
        'Migrated legacy system to microservices, reducing downtime by 99.9%.',
      ],
    },
    {
      id: 'e-2',
      company: 'TechStart Inc',
      role: 'Software Engineer',
      location: 'Portland, OR',
      startDate: '2019-06',
      endDate: '2020-12',
      current: false,
      bullets: [
        'Developed REST APIs using Node.js and Express, handling 10k+ requests daily.',
        'Implemented CI/CD pipelines with GitHub Actions, cutting deployment time by 50%.',
      ],
    },
    {
      id: 'e-3',
      company: 'WebSolutions LLC',
      role: 'Junior Developer',
      location: 'San Francisco, CA',
      startDate: '2018-03',
      endDate: '2019-05',
      current: false,
      bullets: [
        'Built responsive UI components using React and Redux.',
        'Collaborated with UX team to improve page load performance by 40%.',
      ],
    },
  ],
  projects: [
    {
      id: 'p-1',
      name: 'Enterprise Dashboard',
      role: 'Lead Frontend Engineer',
      startDate: '2023-01',
      endDate: '',
      description:
        'A real-time analytics dashboard for enterprise clients with role-based access control and customizable widgets.',
      technologies: 'Angular, NgRx, D3.js, Socket.IO, AWS',
      link: 'https://example.com/enterprise-dashboard',
      bullets: [
        'Designed and implemented 20+ reusable components.',
        'Optimized rendering performance for datasets up to 100k rows.',
      ],
    },
    {
      id: 'p-2',
      name: 'API Gateway Platform',
      role: 'Full Stack Developer',
      startDate: '2022-04',
      endDate: '2022-12',
      description:
        'A microservices-based API gateway with rate limiting, authentication, and monitoring capabilities.',
      technologies: 'Node.js, Express, PostgreSQL, Redis, Docker, Kubernetes',
      link: 'https://example.com/api-gateway',
      bullets: ['Implemented JWT authentication and authorization middleware.', 'Configured auto-scaling on AWS EKS.'],
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of Washington',
      degree: 'B.S.',
      field: 'Computer Science',
      startDate: '2014-09',
      endDate: '2018-06',
      gpa: '3.8',
    },
  ],
  certifications: [
    {
      id: 'c-1',
      name: 'AWS Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issueDate: '2023-01',
      doesNotExpire: false,
      expiryDate: '2026-01',
      credentialId: 'AWS-123ABC',
      credentialUrl: 'https://aws.amazon.com/certification',
    },
    {
      id: 'c-2',
      name: 'Certified Kubernetes Administrator',
      issuer: 'Cloud Native Computing Foundation',
      issueDate: '2022-06',
      doesNotExpire: false,
      expiryDate: '2025-06',
      credentialId: 'CNCF-456DEF',
      credentialUrl: 'https://www.cncf.io/certification',
    },
  ],
  awards: [
    {
      id: 'a-1',
      title: 'Employee of the Year',
      issuer: 'Acme Corp',
      date: '2023',
      description:
        'Awarded for outstanding performance, technical leadership, and mentoring contributions.',
    },
    {
      id: 'a-2',
      title: 'Innovation Award',
      issuer: 'TechStart Inc',
      date: '2020',
      description: 'Recognized for developing a CI/CD pipeline that reduced deployment time by 50%.',
    },
  ],
  achievements: [
    { id: 'ach-1', text: 'Shipped 10+ features in Q1 2024, all with zero production bugs.' },
    { id: 'ach-2', text: 'Achieved 99.99% uptime for Acme Portal over 12-month period.' },
  ],
  languages: [
    { id: 'lang-1', name: 'English', proficiency: 'Native' },
    { id: 'lang-2', name: 'Spanish', proficiency: 'Conversational' },
  ],
  customSections: [
    {
      id: 'cs-1',
      heading: 'Open Source',
      items: [
        'Contributed to Angular CLI.',
        'Maintained an open-source resume-builder library with 500+ stars.',
      ],
    },
  ],
};

/** Dense content guaranteed to overflow a single A4 page for every layout. */
export const longContent: ResumeContent = {
  contacts: {
    fullName: 'Jane Doe',
    title: 'Senior Software Engineer',
    email: 'jane@example.com',
    phone: '+1 555 0100',
    location: 'Seattle, WA',
    linkedinUrl: 'https://linkedin.com/in/janedoe',
    githubUrl: 'https://github.com/janedoe',
    portfolioUrl: 'https://example.com/portfolio',
  },
  summary:
    'Results-driven Senior Software Engineer with 12+ years of experience architecting and shipping scalable web applications. Proven track record of leading cross-functional teams, driving platform migrations, and improving developer velocity across fast-moving product organisations.',
  skills: [
    'Angular',
    'TypeScript',
    'Node.js',
    'Python',
    'AWS',
    'React',
    'PostgreSQL',
    'Docker',
    'Kubernetes',
    'GraphQL',
    'Redis',
    'Terraform',
    'CI/CD',
    'Observability',
  ],
  experiences: [
    {
      id: 'e-1',
      company: 'Acme Corp',
      role: 'Senior Software Engineer',
      location: 'Seattle, WA',
      startDate: '2021-01',
      endDate: '',
      current: true,
      bullets: [
        'Led architecture for customer portal serving 500k+ monthly active users.',
        'Mentored a team of 5 engineers, improving team velocity by 30%.',
        'Migrated legacy system to microservices, reducing downtime by 99.9%.',
        'Introduced a design-system component library reused across 4 squads.',
      ],
    },
    {
      id: 'e-2',
      company: 'TechStart Inc',
      role: 'Staff Software Engineer',
      location: 'Portland, OR',
      startDate: '2019-06',
      endDate: '2020-12',
      current: false,
      bullets: [
        'Developed REST APIs using Node.js and Express, handling 10k+ requests daily.',
        'Implemented CI/CD pipelines with GitHub Actions, cutting deployment time by 50%.',
        'Owned the observability roadmap: tracing, metrics and alerting for 30+ services.',
      ],
    },
    {
      id: 'e-3',
      company: 'WebSolutions LLC',
      role: 'Senior Full Stack Developer',
      location: 'San Francisco, CA',
      startDate: '2017-04',
      endDate: '2019-05',
      current: false,
      bullets: [
        'Built real-time collaboration features used by 40k concurrent users.',
        'Reduced first-paint time by 45% through code-splitting and caching.',
        'Led accessibility remediation across the flagship product.',
      ],
    },
    {
      id: 'e-4',
      company: 'CloudWorks',
      role: 'Full Stack Developer',
      location: 'Austin, TX',
      startDate: '2015-03',
      endDate: '2017-03',
      current: false,
      bullets: [
        'Delivered a multi-tenant SaaS platform from zero to GA in 9 months.',
        'Automated infrastructure provisioning with Terraform on AWS.',
        'Mentored junior developers and ran weekly technical design reviews.',
      ],
    },
    {
      id: 'e-5',
      company: 'Northstar Digital',
      role: 'Software Developer',
      location: 'Chicago, IL',
      startDate: '2013-06',
      endDate: '2015-02',
      current: false,
      bullets: [
        'Shipped 15+ client projects across e-commerce and media.',
        'Contributed to an internal web framework used by 6 product teams.',
      ],
    },
    {
      id: 'e-6',
      company: 'Brightpath',
      role: 'Junior Developer',
      location: 'Denver, CO',
      startDate: '2012-01',
      endDate: '2013-05',
      current: false,
      bullets: [
        'Fixed 200+ production defects and improved test coverage to 85%.',
        'Supported on-call rotations for the core billing service.',
      ],
    },
  ],
  projects: [
    {
      id: 'p-1',
      name: 'Enterprise Dashboard',
      role: 'Lead Frontend Engineer',
      startDate: '2023-01',
      endDate: '',
      description:
        'A real-time analytics dashboard for enterprise clients with role-based access control and customizable widgets.',
      technologies: 'Angular, NgRx, D3.js, Socket.IO, AWS',
      link: 'https://example.com/enterprise-dashboard',
      bullets: [
        'Designed and implemented 20+ reusable components.',
        'Optimized rendering performance for datasets up to 100k rows.',
      ],
    },
    {
      id: 'p-2',
      name: 'API Gateway Platform',
      role: 'Full Stack Developer',
      startDate: '2022-04',
      endDate: '2022-12',
      description:
        'A microservices-based API gateway with rate limiting, authentication, and monitoring capabilities.',
      technologies: 'Node.js, Express, PostgreSQL, Redis, Docker, Kubernetes',
      link: 'https://example.com/api-gateway',
      bullets: [
        'Implemented JWT authentication and authorization middleware.',
        'Configured auto-scaling on AWS EKS.',
      ],
    },
    {
      id: 'p-3',
      name: 'Open Source Toolkit',
      role: 'Maintainer',
      startDate: '2021-05',
      endDate: '',
      description:
        'A collection of validation and formatting libraries used by 40k+ developers worldwide.',
      technologies: 'TypeScript, Vitest, Rollup',
      link: 'https://example.com/opensource',
      bullets: ['Cross-posted releases across npm and GitHub.', 'Reviewed 300+ community PRs.'],
    },
    {
      id: 'p-4',
      name: 'Realtime Editor',
      role: 'Architect',
      startDate: '2020-02',
      endDate: '2021-02',
      description:
        'A collaborative rich-text editor with optimistic updates and offline support.',
      technologies: 'React, Yjs, WebRTC',
      link: 'https://example.com/realtime-editor',
      bullets: ['Designed the CRDT-based sync protocol.', 'Cut latency from 800ms to 40ms.'],
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of Washington',
      degree: 'M.S.',
      field: 'Computer Science',
      startDate: '2010-09',
      endDate: '2012-06',
      gpa: '3.9',
    },
    {
      id: 'edu-2',
      institution: 'State University',
      degree: 'B.S.',
      field: 'Software Engineering',
      startDate: '2006-09',
      endDate: '2010-06',
      gpa: '3.7',
    },
  ],
  certifications: [
    {
      id: 'c-1',
      name: 'AWS Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issueDate: '2023-01',
      doesNotExpire: false,
      expiryDate: '2026-01',
      credentialId: 'AWS-123ABC',
      credentialUrl: 'https://aws.amazon.com/certification',
    },
    {
      id: 'c-2',
      name: 'Certified Kubernetes Administrator',
      issuer: 'Cloud Native Computing Foundation',
      issueDate: '2022-06',
      doesNotExpire: false,
      expiryDate: '2025-06',
      credentialId: 'CNCF-456DEF',
      credentialUrl: 'https://www.cncf.io/certification',
    },
    {
      id: 'c-3',
      name: 'Professional Scrum Master I',
      issuer: 'Scrum.org',
      issueDate: '2021-08',
      doesNotExpire: true,
      expiryDate: '',
      credentialId: 'PSM-789GHI',
      credentialUrl: 'https://www.scrum.org',
    },
    {
      id: 'c-4',
      name: 'Google Professional Cloud Developer',
      issuer: 'Google Cloud',
      issueDate: '2020-11',
      doesNotExpire: false,
      expiryDate: '2024-11',
      credentialId: 'GCP-012JKL',
      credentialUrl: 'https://cloud.google.com/certification',
    },
  ],
  awards: [
    {
      id: 'a-1',
      title: 'Employee of the Year',
      issuer: 'Acme Corp',
      date: '2023',
      description:
        'Awarded for outstanding performance, technical leadership, and mentoring contributions.',
    },
    {
      id: 'a-2',
      title: 'Innovation Award',
      issuer: 'TechStart Inc',
      date: '2020',
      description: 'Recognized for developing a CI/CD pipeline that reduced deployment time by 50%.',
    },
    {
      id: 'a-3',
      title: 'Community Contributor',
      issuer: 'Open Source Foundation',
      date: '2021',
      description: 'Awarded for sustained high-quality contributions to open-source libraries.',
    },
  ],
  achievements: [
    { id: 'ach-1', text: 'Shipped 40+ features in two years, all with zero production defects.' },
    { id: 'ach-2', text: 'Achieved 99.99% uptime for Acme Portal over a 12-month period.' },
    { id: 'ach-3', text: 'Reduced cloud spend by 35% through workload right-sizing.' },
    { id: 'ach-4', text: 'Published 12 technical articles with 250k+ total reads.' },
  ],
  languages: [
    { id: 'lang-1', name: 'English', proficiency: 'Native' },
    { id: 'lang-2', name: 'Spanish', proficiency: 'Professional' },
    { id: 'lang-3', name: 'German', proficiency: 'Conversational' },
  ],
  customSections: [
    {
      id: 'cs-1',
      heading: 'Open Source',
      items: [
        'Contributed to Angular CLI.',
        'Maintained an open-source resume-builder library with 500+ stars.',
        'Reviewed 300+ community pull requests across three projects.',
      ],
    },
    {
      id: 'cs-2',
      heading: 'Speaking',
      items: [
        'Delivered a conference talk on scalable front-end architecture.',
        'Led an internal workshop on observability for 60 engineers.',
      ],
    },
  ],
};

/** Sparse content exercising empty/partial rendering in generated previews. */
export const sparseContent: ResumeContent = {
  contacts: {
    fullName: 'Alex Rivera',
    title: 'Systems Administrator',
    email: 'alex@example.com',
    phone: '',
    location: '',
    linkedinUrl: '',
    githubUrl: '',
    portfolioUrl: '',
  },
  summary: '',
  skills: [],
  experiences: [],
  projects: [],
  education: [],
  certifications: [],
  awards: [],
  achievements: [],
  languages: [],
  customSections: [],
};
