import { Page } from '@playwright/test';

export interface WaitForPreviewReadyOptions {
  /**
   * Selector of the shared preview stage iframe. Defaults to the A4 preview
   * frame used by Template Preview and Create Resume.
   */
  iframeSelector?: string;
  /**
   * How long to wait for the preview to reach a stable Fit state.
   */
  timeout?: number;
  /**
   * The preview must expose the pagination report generated by the embedded
   * page-splitting script before it counts as ready.
   */
  requirePaginationReport?: boolean;
}

/**
 * Waits for the shared A4 preview to reach a deterministically ready state
 * before tests measure it. Readiness is observed, never slept for:
 *
 *  - the iframe is attached and its document is available with resume pages,
 *  - fonts are settled in both the host page and the iframe document,
 *  - the Fit calculation has been applied (the scaled canvas fits its stage),
 *  - animations/transitions are disabled so Fit settles immediately,
 *  - the pagination report exists (the page-splitting script finished),
 *  - there is no horizontal overflow in the stage or the iframe document,
 *  - the stage/canvas/frame dimensions are stable across two consecutive
 *    measurements.
 *
 * Fails loudly with the stage state snapshot if the preview never settles, so
 * a regression points at the real cause instead of a flaky timeout.
 */
export async function waitForPreviewReady(
  page: Page,
  options: WaitForPreviewReadyOptions = {},
): Promise<void> {
  const iframeSelector = options.iframeSelector ?? 'iframe.preview-frame__iframe';
  const timeout = options.timeout ?? 15_000;
  const requirePaginationReport = options.requirePaginationReport ?? true;

  const iframe = page.locator(iframeSelector);
  await iframe.waitFor({ state: 'attached', timeout });

  // Animations and transitions are disabled during E2E so the Fit transform
  // settles on its final value instead of being caught mid-transition.
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.addStyleTag({
    content:
      '*, *::before, *::after { transition-duration: 0.001s !important; animation-duration: 0.001s !important; }',
  });

  // The iframe must be loaded with its document available and resume pages.
  await page.waitForFunction(
    (sel) => {
      const el = document.querySelector(sel) as HTMLIFrameElement | null;
      if (!el || !el.contentDocument) {
        return false;
      }
      return el.contentDocument.querySelector('.resume-page') !== null;
    },
    iframeSelector,
    { timeout },
  );

  // Fonts must be settled so Fit measures real layout metrics.
  await iframe.evaluate(async (el) => {
    const frame = el as HTMLIFrameElement;
    await document.fonts.ready;
    const doc = frame.contentDocument;
    if (doc) {
      await doc.fonts.ready;
    }
  });

  // Poll for the stable Fit state: same dimensions on two consecutive reads,
  // with the fit applied and no horizontal overflow anywhere.
  const deadline = Date.now() + timeout;
  let previous: string | null = null;
  while (Date.now() < deadline) {
    const snapshot = await iframe.evaluate((el, requireReport) => {
      const frame = el as HTMLIFrameElement;
      const stage = frame.closest('.preview-frame') as HTMLElement | null;
      const doc = frame.contentDocument;
      const win = frame.contentWindow;
      if (!stage || !doc || !win) {
        return null;
      }
      const canvas = stage.querySelector('.preview-frame__canvas') as HTMLElement | null;
      if (!canvas) {
        return null;
      }
      const stageRect = stage.getBoundingClientRect();
      const canvasRect = canvas.getBoundingClientRect();
      if (canvasRect.width <= 0 || canvasRect.height <= 0) {
        return null;
      }
      // Fit applied: the scaled canvas fits inside its stage.
      if (canvasRect.width > stageRect.width + 1 || canvasRect.height > stageRect.height + 1) {
        return null;
      }
      // No horizontal overflow in the stage or the iframe document.
      if (stage.scrollWidth - stage.clientWidth > 1) {
        return null;
      }
      if (doc.documentElement.scrollWidth - doc.documentElement.clientWidth > 1) {
        return null;
      }
      // The pagination script finished if its report is expected.
      if (
        requireReport &&
        !(win as unknown as { __paginationReport?: unknown }).__paginationReport
      ) {
        return null;
      }
      return JSON.stringify({
        stage: [stage.clientWidth, stage.clientHeight, stage.scrollWidth],
        canvas: [Math.round(canvasRect.width), Math.round(canvasRect.height)],
        frame: [
          Math.round(frame.getBoundingClientRect().width),
          Math.round(frame.getBoundingClientRect().height),
        ],
        scale: window.getComputedStyle(frame).transform,
      });
    }, requirePaginationReport);

    if (snapshot !== null) {
      if (previous === snapshot) {
        return;
      }
      previous = snapshot;
    }
    await page.waitForTimeout(50);
  }

  throw new Error(
    `Preview did not reach a stable Fit state within ${timeout}ms. ` +
      `Last measured state: ${previous ?? 'no measurable state'}.`,
  );
}
