import { chromium } from 'playwright';
import { LAYOUT_ORDER, LAYOUT_META, CATEGORY_ORDER } from '../src/app/core/templates/template-catalogue';
import { TemplateCategory } from '../src/app/core/models/template-definition.model';
import * as path from 'path';
import * as fs from 'fs';

const SCREENSHOT_DIR = path.join(__dirname, '..', 'screenshots');
const THUMBNAIL_DIR = path.join(__dirname, '..', 'public', 'template-thumbnails');

const CATEGORY_SLUG: Record<TemplateCategory, string> = {
  [TemplateCategory.AtsFormal]: 'ats-formal',
  [TemplateCategory.Modern]: 'modern',
  [TemplateCategory.Technical]: 'technical',
  [TemplateCategory.Executive]: 'executive',
  [TemplateCategory.CreativeMinimal]: 'creative-minimal',
};

function thumbnailPath(family: string): string {
  const abs = path.join(THUMBNAIL_DIR, `t-${family}-navy.png`);
  return `file:///${abs.replace(/\\/g, '/')}`;
}

function cardHtml(family: string): string {
  const meta = LAYOUT_META[family as keyof typeof LAYOUT_META];
  const badge = meta.badge === 'ats' ? 'ATS' : 'Visual';
  return `<div class="card"><img src="${thumbnailPath(family)}" alt="${meta.name}"><div class="meta"><strong>${meta.name}</strong><span class="badge ${meta.badge}">${badge}</span></div></div>`;
}

function sheetHtml(title: string, families: string[]): string {
  const cards = families.map(cardHtml).join('\n');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; padding: 12px; background: #f1f5f9; }
    h1 { font-size: 16px; margin: 0 0 4px; }
    p { font-size: 12px; color: #475569; margin: 0 0 10px; }
    .grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; }
    .card { background: #fff; border: 1px solid #cbd5e1; border-radius: 8px; overflow: hidden; }
    .card img { width: 100%; display: block; }
    .meta { padding: 6px 8px; font-size: 11px; display: flex; align-items: center; justify-content: space-between; gap: 6px; }
    .badge { border-radius: 999px; padding: 1px 6px; font-size: 9px; font-weight: 700; }
    .badge.ats { background: #dcfce7; color: #166534; }
    .badge.visual { background: #e0e7ff; color: #3730a3; }
  </style></head><body><h1>${title}</h1><p>Generated by scripts/contact-sheet.ts · ${families.length} layouts · Navy theme</p><div class="grid">${cards}</div></body></html>`;
}

async function screenshotHtml(file: string, html: string, width: number): Promise<void> {
  const htmlPath = path.join(SCREENSHOT_DIR, file);
  fs.writeFileSync(htmlPath, html, 'utf-8');
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width, height: 900 } });
  await page.goto(`file:///${htmlPath.replace(/\\/g, '/')}`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(400);
  const pngPath = htmlPath.replace(/\.html$/, '.png');
  await page.screenshot({ path: pngPath, fullPage: true });
  await page.close();
  await browser.close();
  console.log(`Contact sheet saved: ${pngPath} (${width}px)`);
}

async function main(): Promise<void> {
  const widthArg = process.argv.indexOf('--width');
  const width = widthArg >= 0 ? Number(process.argv[widthArg + 1]) : 4100;
  if (!Number.isFinite(width) || width <= 0) {
    console.error('Invalid --width value.');
    process.exit(1);
  }

  if (!fs.existsSync(SCREENSHOT_DIR)) {
    fs.mkdirSync(SCREENSHOT_DIR, { recursive: true });
  }

  for (const category of CATEGORY_ORDER) {
    const families = LAYOUT_ORDER.filter((f) => LAYOUT_META[f].category === category);
    const file = `contact-sheet-${CATEGORY_SLUG[category]}.html`;
    await screenshotHtml(file, sheetHtml(`ResumeIQ — ${category} Layouts`, families), width);
  }

  const overview = LAYOUT_ORDER.filter((f) => LAYOUT_META[f].badge === 'ats');
  await screenshotHtml(
    'contact-sheet-ats.html',
    sheetHtml('ResumeIQ — ATS-friendly Layouts', overview),
    width,
  );

  await screenshotHtml('contact-sheet-all.html', sheetHtml('ResumeIQ — All 25 Layouts (Navy)', [...LAYOUT_ORDER]), width);
  console.log('Done. Contact sheets generated.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
