import { ResumeContent } from './resume.model';

function hasText(value: string | undefined | null): boolean {
  return typeof value === 'string' && value.trim().length > 0;
}

/**
 * Identity fields and toggle booleans are always generated by the form and
 * carry no user-supplied information, so they are ignored when deciding
 * whether an entry holds real content.
 */
const NON_CONTENT_KEYS: readonly string[] = ['id', 'current', 'doesNotExpire'];

/** True when a resume entry (experience, project, education, ...) holds any
 * visible text beyond its generated id / toggle flags. */
function entryHasContent(entry: object): boolean {
  for (const [key, value] of Object.entries(entry)) {
    if (NON_CONTENT_KEYS.includes(key)) {
      continue;
    }
    if (typeof value === 'string' && value.trim().length > 0) {
      return true;
    }
    if (Array.isArray(value) && value.some((item) => hasText(item))) {
      return true;
    }
  }
  return false;
}

/**
 * True when a resume version carries no user-supplied content at all (i.e. it
 * is a freshly created blank master version). Used by the mock ATS analysis to
 * return a realistic low score for empty resumes instead of the fixed
 * high-scoring fixture that mirrors the seeded sample.
 */
export function isContentEmpty(content: ResumeContent): boolean {
  if (hasText(content.summary)) {
    return false;
  }
  if (content.skills.some((skill) => hasText(skill))) {
    return false;
  }
  if (
    hasText(content.contacts.fullName) ||
    hasText(content.contacts.title) ||
    hasText(content.contacts.email) ||
    hasText(content.contacts.phone) ||
    hasText(content.contacts.location) ||
    hasText(content.contacts.linkedinUrl) ||
    hasText(content.contacts.githubUrl) ||
    hasText(content.contacts.portfolioUrl)
  ) {
    return false;
  }

  const groups: readonly (readonly object[])[] = [
    content.experiences,
    content.projects,
    content.education,
    content.certifications,
    content.awards,
    content.achievements,
    content.languages,
    content.customSections,
  ];
  return !groups.some((group) => group.some((entry) => entryHasContent(entry)));
}
