import { z } from 'zod';
import { PdfValidationError } from './errors';

/** Maximum serialized JSON size of a resume content payload (bytes). */
export const MAX_PDF_CONTENT_BYTES = 512 * 1024;

const idField = z.string().max(80);
const shortText = z.string().max(5000);
const urlText = z.string().max(2000);
const nameText = z.string().max(300);
const bullets = z.array(shortText).max(50);
const dateStr = z.string().max(20);

const experienceEntry = z.strictObject({
  id: idField,
  company: nameText,
  role: nameText,
  location: nameText,
  startDate: dateStr,
  endDate: dateStr,
  current: z.boolean(),
  bullets,
});

const projectEntry = z.strictObject({
  id: idField,
  name: nameText,
  role: nameText,
  startDate: dateStr,
  endDate: dateStr,
  description: shortText,
  technologies: nameText,
  link: urlText,
  bullets,
});

const educationEntry = z.strictObject({
  id: idField,
  institution: nameText,
  degree: nameText,
  field: nameText,
  startDate: dateStr,
  endDate: dateStr,
  gpa: nameText,
});

const certificationEntry = z.strictObject({
  id: idField,
  name: nameText,
  issuer: nameText,
  issueDate: dateStr,
  doesNotExpire: z.boolean(),
  expiryDate: dateStr,
  credentialId: nameText,
  credentialUrl: urlText,
});

const awardEntry = z.strictObject({
  id: idField,
  title: nameText,
  issuer: nameText,
  date: dateStr,
  description: shortText,
});

const customSection = z.strictObject({
  id: idField,
  heading: nameText,
  items: bullets,
});

const achievementEntry = z.strictObject({
  id: idField,
  text: shortText,
});

const languageEntry = z.strictObject({
  id: idField,
  name: nameText,
  proficiency: nameText,
});

/**
 * Runtime schema for the structured resume payload the client sends instead
 * of rendered HTML. Mirrors the shared `ResumeContent` model. `strictObject`
 * rejects unknown keys (including the legacy `html` field) so the endpoint
 * stays a resume renderer, not a general HTML-to-PDF service.
 */
export const ResumeContentSchema = z.strictObject({
  contacts: z.strictObject({
    fullName: nameText,
    title: nameText.optional(),
    email: z.string().max(300),
    phone: z.string().max(60),
    location: nameText,
    linkedinUrl: urlText,
    githubUrl: urlText,
    portfolioUrl: urlText,
  }),
  summary: z.string().max(8000),
  skills: z.array(nameText).max(100),
  experiences: z.array(experienceEntry).max(60),
  projects: z.array(projectEntry).max(60),
  education: z.array(educationEntry).max(40),
  certifications: z.array(certificationEntry).max(40),
  awards: z.array(awardEntry).max(40),
  achievements: z.array(achievementEntry).max(60),
  languages: z.array(languageEntry).max(30),
  customSections: z.array(customSection).max(30),
});

export type ResumeContentPayload = z.infer<typeof ResumeContentSchema>;

/**
 * Identity fields and toggle booleans are always generated by the client form
 * and carry no user-supplied information, so they are ignored when deciding
 * whether an entry holds real content.
 */
const NON_CONTENT_KEYS: readonly string[] = ['id', 'current', 'doesNotExpire'];

function hasText(value: string | undefined | null): boolean {
  return typeof value === 'string' && value.trim().length > 0;
}

/** True when a resume entry (experience, project, education, ...) holds any
 * visible text beyond its generated id / toggle flags. */
function entryHasContent(entry: object): boolean {
  for (const [key, value] of Object.entries(entry)) {
    if (NON_CONTENT_KEYS.includes(key)) {
      continue;
    }
    if (typeof value === 'string' && value.trim().length > 0) {
      return true;
    }
    if (Array.isArray(value) && value.some((item) => hasText(item))) {
      return true;
    }
  }
  return false;
}

/**
 * True when the resume carries no user-supplied content (a freshly created
 * blank version). Exporting such a version would produce a PDF with nothing
 * useful in it, so the controller rejects it with a clear message instead.
 */
export function isResumeContentEmpty(content: ResumeContentPayload): boolean {
  if (hasText(content.summary)) {
    return false;
  }
  if (content.skills.some((skill) => hasText(skill))) {
    return false;
  }
  if (
    hasText(content.contacts.fullName) ||
    hasText(content.contacts.title) ||
    hasText(content.contacts.email) ||
    hasText(content.contacts.phone) ||
    hasText(content.contacts.location) ||
    hasText(content.contacts.linkedinUrl) ||
    hasText(content.contacts.githubUrl) ||
    hasText(content.contacts.portfolioUrl)
  ) {
    return false;
  }

  const groups: ReadonlyArray<ReadonlyArray<object>> = [
    content.experiences,
    content.projects,
    content.education,
    content.certifications,
    content.awards,
    content.achievements,
    content.languages,
    content.customSections,
  ];
  return !groups.some((group) => group.some((entry) => entryHasContent(entry)));
}

/**
 * Validates an untyped request body as resume content. Enforces the JSON size
 * limit and throws PdfValidationError (HTTP 400) when invalid.
 */
export function assertValidResumeContent(
  raw: unknown,
  maxBytes = MAX_PDF_CONTENT_BYTES
): ResumeContentPayload {
  const serialized = JSON.stringify(raw ?? null) ?? '';
  if (Buffer.byteLength(serialized, 'utf8') > maxBytes) {
    throw new PdfValidationError(
      `Resume content payload is too large (${Buffer.byteLength(serialized, 'utf8')} bytes).`
    );
  }

  const parsed = ResumeContentSchema.safeParse(raw);
  if (!parsed.success) {
    const firstIssue = parsed.error.issues[0];
    const detail = firstIssue
      ? `${firstIssue.path.join('.') || 'payload'} ${firstIssue.message}`
      : 'Invalid resume content.';
    throw new PdfValidationError(`Invalid resume content: ${detail}`);
  }
  return parsed.data;
}
