/**
 * GENERATED FILE — do not edit by hand.
 *
 * ATS-relevant template metadata shared by every package. Generated from the
 * canonical frontend template catalogue by running
 * `npx tsx scripts/generate-ats-template-catalogue.ts` in the backend directory.
 */

export interface TemplateAtsProfile {
  id: string;
  isAtsFriendly: boolean;
  isVisual: boolean;
  columnCount: number;
}

export const ATS_TEMPLATE_PROFILES: readonly TemplateAtsProfile[] = [
  { id: 't-classic-ats-navy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-classic-ats-charcoal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-classic-ats-teal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-classic-ats-burgundy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-compact-ats-navy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-compact-ats-charcoal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-compact-ats-teal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-compact-ats-burgundy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-corporate-standard-navy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-corporate-standard-charcoal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-corporate-standard-teal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-corporate-standard-burgundy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-academic-cv-navy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-academic-cv-charcoal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-academic-cv-teal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-academic-cv-burgundy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-legal-formal-navy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-legal-formal-charcoal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-legal-formal-teal', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-legal-formal-burgundy', isAtsFriendly: true, isVisual: false, columnCount: 1 },
  { id: 't-premium-sidebar-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-premium-sidebar-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-premium-sidebar-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-premium-sidebar-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-modern-split-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-modern-split-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-modern-split-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-modern-split-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-centered-header-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-centered-header-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-centered-header-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-centered-header-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-accent-timeline-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-accent-timeline-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-accent-timeline-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-accent-timeline-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-clean-cards-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-clean-cards-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-clean-cards-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-clean-cards-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-developer-console-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-developer-console-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-developer-console-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-developer-console-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-product-engineer-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-product-engineer-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-product-engineer-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-product-engineer-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-data-analyst-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-data-analyst-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-data-analyst-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-data-analyst-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-cloud-architect-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-cloud-architect-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-cloud-architect-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-cloud-architect-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-cybersecurity-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-cybersecurity-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-cybersecurity-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-cybersecurity-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-executive-banner-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-executive-banner-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-executive-banner-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-executive-banner-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-leadership-profile-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-leadership-profile-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-leadership-profile-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-leadership-profile-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-boardroom-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-boardroom-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-boardroom-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-boardroom-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-strategy-consultant-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-strategy-consultant-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-strategy-consultant-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-strategy-consultant-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-finance-professional-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-finance-professional-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-finance-professional-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-finance-professional-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-swiss-minimal-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-swiss-minimal-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-swiss-minimal-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-swiss-minimal-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-editorial-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-editorial-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-editorial-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-editorial-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-geometric-accent-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-geometric-accent-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-geometric-accent-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-geometric-accent-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-soft-neutral-navy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-soft-neutral-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-soft-neutral-teal', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-soft-neutral-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 2 },
  { id: 't-creative-portfolio-navy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-creative-portfolio-charcoal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-creative-portfolio-teal', isAtsFriendly: false, isVisual: true, columnCount: 1 },
  { id: 't-creative-portfolio-burgundy', isAtsFriendly: false, isVisual: true, columnCount: 1 },
];

export const DEFAULT_ATS_TEMPLATE_ID = 't-classic-ats-navy';
